/* oxlint-disable next/no-img-element -- Private authenticated and local object URLs must bypass image optimization. */
'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useData } from './data-provider';
import { displayName, categories, safeFilename } from '@/lib/domain';
import { errorText, fileUrl } from '@/lib/client';
export function GeneratedHistory() {
  const { generations } = useData();
  const [category, setCategory] = useState('');
  const [selected, setSelected] = useState<string[]>([]);
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState('');
  const [error, setError] = useState('');
  const records = generations.filter(
    (record) => !category || record.member.membership_type === category,
  );
  async function action(fn: () => Promise<void>) {
    setBusy(true);
    setError('');
    try {
      await fn();
    } catch (error) {
      setError(errorText(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <div className="mt-6 space-y-4">
      <div className="flex flex-wrap items-end gap-3">
        <label className="field">
          Membership
          <select
            aria-label="Membership"
            value={category}
            onChange={(event) => setCategory(event.target.value)}
          >
            <option value="">All</option>
            {categories.map((value) => (
              <option key={value}>{value}</option>
            ))}
          </select>
        </label>
        <button
          className="btn-primary"
          disabled={busy || !selected.length}
          onClick={() =>
            void action(async () => {
              const { exportZip } = await import('@/lib/export-id');
              await exportZip(
                generations.filter((record) => selected.includes(record.id)),
                setProgress,
              );
              setProgress('ZIP downloaded.');
            })
          }
        >
          Download selected ZIP
        </button>
      </div>
      {progress && <output className="block">{progress}</output>}
      {error && (
        <p className="notice-error" role="alert">
          {error}
        </p>
      )}
      <div className="overflow-auto rounded-2xl border bg-white">
        <table className="data-table">
          <thead>
            <tr>
              <th>
                <input
                  type="checkbox"
                  aria-label="Select all displayed generations"
                  checked={
                    !!records.length &&
                    records.every((record) => selected.includes(record.id))
                  }
                  onChange={(event) =>
                    setSelected(
                      event.target.checked
                        ? records.map((record) => record.id)
                        : [],
                    )
                  }
                />
              </th>
              {[
                'Member',
                'Classification',
                'AWS SBG ID',
                'Generated',
                'Valid until',
                'Generated by',
                'Version',
                'Status',
                'Files',
              ].map((label) => (
                <th key={label}>{label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {records.map((record) => (
              <tr key={record.id}>
                <td>
                  <input
                    type="checkbox"
                    aria-label={`Select generation ${record.id}`}
                    checked={selected.includes(record.id)}
                    onChange={(event) =>
                      setSelected(
                        event.target.checked
                          ? [...selected, record.id]
                          : selected.filter((id) => id !== record.id),
                      )
                    }
                  />
                </td>
                <td>
                  <div className="flex min-w-44 items-center gap-2">
                    {record.member.photo_path && (
                      <img
                        alt=""
                        src={fileUrl(record.member.photo_path)}
                        className="size-10 rounded-full object-cover"
                      />
                    )}
                    {displayName(record.member)}
                  </div>
                </td>
                <td>
                  {record.member.membership_type}
                  <br />
                  {record.member.team}
                  <br />
                  {record.member.officer_position}
                </td>
                <td>{record.member.aws_sbg_id}</td>
                <td>{new Date(record.generated_at).toLocaleString()}</td>
                <td>{record.member.valid_until ?? 'Not issued'}</td>
                <td>{record.generated_by}</td>
                <td className="max-w-40 break-all text-xs">
                  {record.template_version}
                </td>
                <td>
                  {record.status}
                  <br />
                  <span
                    style={{ background: record.accent }}
                    className="inline-block size-4 rounded-full"
                    aria-label={`Accent ${record.accent}`}
                  />
                </td>
                <td>
                  <div className="flex min-w-60 flex-wrap gap-2">
                    <a
                      className="btn"
                      href={fileUrl(record.front_path!)}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Preview front
                    </a>
                    {record.back_path && (
                      <a
                        className="btn"
                        href={fileUrl(record.back_path)}
                        target="_blank"
                        rel="noreferrer"
                      >
                        Preview back
                      </a>
                    )}
                    {[
                      ['front.png', record.front_path],
                      ['back.png', record.back_path],
                      ['ID.pdf', record.pdf_path],
                    ].filter(([, path]) => path).map(([file, path]) => (
                      <button
                        className="btn"
                        key={file}
                        disabled={busy}
                        onClick={() =>
                          void action(async () => {
                            const { downloadFile } =
                              await import('@/lib/export-id');
                            await downloadFile(
                              path!,
                              `${safeFilename(record.member)}_${file}`,
                            );
                          })
                        }
                      >
                        Download {file}
                      </button>
                    ))}
                    <Link
                      className="btn"
                      href={`/generate-id?member=${record.member_id}`}
                    >
                      Review / Regenerate
                    </Link>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {!records.length && (
          <p className="p-8 text-center text-slate-600">
            No generated IDs yet. Review and confirm members before generation.
          </p>
        )}
      </div>
    </div>
  );
}
