import type { Member } from '@/lib/types';

export const members: Member[] = [
  {
    id: 'AWSSBG-TIPM-26020',
    fullName: 'Maria Allyza A. Toquire',
    email: 'mmatoquire@tip.edu.ph',
    role: 'Member',
    membershipType: 'member',
    photo: '',
    issuedAt: '2026-09-08',
    validUntil: '2027-09-08',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26001',
    fullName: 'Juan Miguel D. Santos',
    email: 'jmdsantos@tip.edu.ph',
    role: 'Chief Executive Officer / Lead',
    membershipType: 'officer',
    photo: '',
    issuedAt: '2026-09-08',
    validUntil: '2027-09-08',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26035',
    fullName: 'Andrea Mae C. Reyes',
    email: 'amcreyes@tip.edu.ph',
    role: 'Associate Member',
    membershipType: 'associate',
    photo: '',
    issuedAt: '2026-09-08',
    validUntil: '2027-09-08',
    idStatus: 'pending',
  },
  {
    id: 'AWSSBG-TIPM-26004',
    fullName: 'Paolo Vincent R. Cruz',
    email: 'pvrcruz@tip.edu.ph',
    role: 'Vice President for Technology',
    membershipType: 'officer',
    photo: '',
    issuedAt: '2026-08-15',
    validUntil: '2027-08-15',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26012',
    fullName: 'Samantha Nicole B. Garcia',
    email: 'snbgarcia@tip.edu.ph',
    role: 'Member',
    membershipType: 'member',
    photo: '',
    issuedAt: '2026-08-20',
    validUntil: '2027-08-20',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26017',
    fullName: 'Kurt Daniel M. Lim',
    email: 'kdmlim@tip.edu.ph',
    role: 'Member',
    membershipType: 'member',
    photo: '',
    issuedAt: '2026-08-21',
    validUntil: '2027-08-21',
    idStatus: 'pending',
  },
  {
    id: 'AWSSBG-TIPM-26007',
    fullName: 'Bianca Louise T. Mendoza',
    email: 'bltmendoza@tip.edu.ph',
    role: 'Vice President for Community',
    membershipType: 'officer',
    photo: '',
    issuedAt: '2026-07-30',
    validUntil: '2027-07-30',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26028',
    fullName: 'Gabriel Luis P. Navarro',
    email: 'glpnavarro@tip.edu.ph',
    role: 'Member',
    membershipType: 'member',
    photo: '',
    issuedAt: '2025-08-01',
    validUntil: '2026-08-01',
    idStatus: 'expired',
  },
  {
    id: 'AWSSBG-TIPM-26039',
    fullName: 'Hannah Sofia L. Ong',
    email: 'hsloong@tip.edu.ph',
    role: 'Associate Member',
    membershipType: 'associate',
    photo: '',
    issuedAt: '2026-09-01',
    validUntil: '2027-09-01',
    idStatus: 'pending',
  },
  {
    id: 'AWSSBG-TIPM-26009',
    fullName: 'Rafael Joaquin E. Flores',
    email: 'rjeflores@tip.edu.ph',
    role: 'Secretary',
    membershipType: 'officer',
    photo: '',
    issuedAt: '2026-08-05',
    validUntil: '2027-08-05',
    idStatus: 'generated',
  },
  {
    id: 'AWSSBG-TIPM-26031',
    fullName: 'Chloe Isabelle M. Tan',
    email: 'cimtan@tip.edu.ph',
    role: 'Member',
    membershipType: 'member',
    photo: '',
    issuedAt: '2025-07-22',
    validUntil: '2026-07-22',
    idStatus: 'expired',
  },
  {
    id: 'AWSSBG-TIPM-26042',
    fullName: 'Nathaniel James A. Sy',
    email: 'njasy@tip.edu.ph',
    role: 'Associate Member',
    membershipType: 'associate',
    photo: '',
    issuedAt: '2026-09-03',
    validUntil: '2027-09-03',
    idStatus: 'pending',
  },
];
